[package]
name = "kumiko-cli"
version = "0.1.0"
edition = "2021"

[dependencies]
libkumiko = { path = "../libkumiko" }
clap = { version = "4.5.4", features = ["derive", "string"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
opener = "0.6"